# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1791acc9d65a245438f12e3d1976a5a5869ce98731ddc937146beac0ecc4cb29b4a4c6440ecfcac9e545c6447fff1c374b3586f75016f17106643261b77823a

test:
  secret_key_base: a4d725cfd854ed00ddfffb654543c33aa602822eeadf4679626d5ec2053411337b172fc8d374463962d0ef18d86ddfeef6f2c69463e844981e5d29fbd3aa2516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
